# Generated by Django 2.0 on 2018-01-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUiAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('res_time', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
