# Generated by Django 2.0 on 2018-01-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useruiacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruiacc',
            name='login',
        ),
        migrations.RemoveField(
            model_name='useruiacc',
            name='password',
        ),
    ]
