# Generated by Django 2.0 on 2018-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180119_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruiacc',
            name='token',
            field=models.CharField(max_length=45),
        ),
    ]
