# Generated by Django 2.0 on 2017-12-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=35)),
            ],
        ),
    ]
